<?php
$dataconfig = array (
  'DEFAULT_LANG' => 'fr',
  'OTHER_LANG1' => 'fr',
  'FQDN' => 'localhost:53080',
  'WWW_GROUP' => 'www-data',
  'TMP_PATH' => '/tmp',
  'KEY' => 'OS',
  'DB_HOST' => 'mysql',
  'DB_PORT' => '3306',
  'DB_USER' => 'rbschange',
  'DB_PASSWORD' => 'rbsch@nge',
  'DB_DATABASE' => 'rbschange',
  'SERVER_MAIL' => 'SMTP',
  'NO_REPLY' => 'noreply@localhost.com',
  'SENDMAIL_PATH' => '/usr/sbin/sendmail',
  'SENDMAIL_ARGS' => '-t -i',
  'SMTP_HOST' => 'mailcatcher',
  'SMTP_PORT' => '1025',
  'SOLR_URL' => 'http://solr:8983/solr',
  'SAMPLES' => 'checked',
  'WEBEDIT_HOME' => '/var/www/rbschange',
  'USEHTTPS' => false,
  'BASEURL' => 'http://localhost:53080',
  'checked' => false,
);
